### ISSUE TITLE
Add CURL Support

### ISSUE THREAD

**Issue by ianvizarra** [ianvizarra/pse-tracker-cli#2]
```bash
curl https://domain.name/{symbol}
```

**Comment by WarenGonzaga** [comment]
@ianvizarra is this plain local CLI? do we need to also support CMD?

**Comment by ianvizarra** [comment]
@WarenGonzaga Yes, it is. We can add CMD support

**Comment by WarenGonzaga** [comment]
@ianvizarra alright... have you already uploaded this to our vercel team account? How about our API is it reliable?
